name: flutter CI 

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
     env:
      REPO_READER_USER : ${{ secrets.REPO_READER_USER }}
      REPO_READER_PASSWORD : ${{ secrets.REPO_READER_PASSWORD }}
     runs-on: "ubuntu-latest"

     steps:

    # Set up Flutter.
       - name: Clone Flutter repository with master channel
         uses: subosito/flutter-action@v1.5.0
         with:
           channel: 'stable'

   # Checkout
       - name: Checkout
         uses: actions/checkout@v2
    
    # Get flutter dependencies.
       - run: flutter pub get
    
    # Statically analyze the Dart code for any errors.
       - run: flutter analyze .


       - name: compile kotlin
         working-directory: example/
         run: flutter build apk 
         
  build_ios:
    name: Build iOS App
    
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Make sure the stable version of Flutter is available
      - uses: subosito/flutter-action@v1.5.0
        with:
          channel: 'stable'

      # Download all Flutter packages
      - name: Download dependencies
        run: flutter pub get

      # Build iOS version of the example App
      - name: Run iOS build
        run: flutter build ios --release --no-codesign
        working-directory: example/