name: flutter CI 

on:
  pull_request:
    branches: [ main ]

jobs:
   build:
     
     runs-on: "ubuntu-latest"

     steps:
    # Set up Flutter.
       - name: Clone Flutter repository with master channel
         uses: subosito/flutter-action@v1.5.0
         with:
           channel: master
          # Checkout gallery code and get packages.
       - name: Checkout
         uses: actions/checkout@v2
    
    # Get flutter dependencies.
       - run: flutter pub get
    
    # Statically analyze the Dart code for any errors.
       - run: flutter analyze .

       - name: compile kotlin
         working-directory: example/
         run: flutter build apk 

       - name: compile ios
         working-directory: example/
         run: flutter build ios 